### ISSUE TITLE
Is deployKF open for contribution?

### ISSUE THREAD

**Issue by oubotong** [deployKF/deployKF#10]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This request is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### Motivation

Hi, I am a huge fan of Kubeflow and it's great to see that DeployKF integrates with it.
I am very interested in making user-friendly MLOps that can be easily deployed to a production environment.

I am wondering if this project is open for contribution cause I am really interested in it! 
If so, is there any guidance that I should follow? Thanks!

### Implementation

I am currently reading the source codes.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@oubotong Absolutely, I have a huge list of tasks which I am planning to migrate into the public issue tracker, and will greatly appreciate the help on those.

But before any of that, the most helpful thing you can do is try deployKF in your environment (bonus points if it's a popular cloud provider), and report back on any issues which make the experience sub-optimal!

If you do plan on making code contributions, please read the [CONTRIBUTING](https://github.com/deployKF/deployKF/blob/main/CONTRIBUTING.md) guide!

**Comment by oubotong** [comment]
@thesuperzapper Thanks!
