### ISSUE TITLE
KFP v2 runs are broken in 2.0.0-alpha7

### ISSUE THREAD

**Issue by pbasov** [deployKF/deployKF#101]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.3

### Kubernetes Version

```shell
1.29.0
```

### Description

Kubeflow v2 pipelines are broken in v2.0.0-alpha7 that is shipped by default with DeployKF.

Google in their infinite wisdom have hardcoded the kfp images here with the `:latest` tag:
https://github.com/kubeflow/pipelines/blob/2.0.0-alpha.7/backend/src/v2/compiler/argocompiler/argo.go#L110-L111

They are not exposed in config in any way, just hardcode, then they proceed to break them somewhere in upstream, making kfp2 unusable for anyone on 2.0.0a7: https://github.com/kubeflow/pipelines/issues/8446

Upgrading to `2.0.0` works in the meanwhile, but for the next deployKF, we need to make sure to be off this version.

I realize that this is not strictly a deployKF issue, but in the latest version said images are parametrized as envvars, so it would be nice to expose these in `sample-values.yaml`:
https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/compiler/argocompiler/container.go#L28-L34

This is important for offline deployments and would be nice to have less dependence on whatever is happening in upstream image repos.

### Relevant Logs

```shell
F0210 01:08:49.734299      17 main.go:74] KFP driver: driver.Container(pipelineName=hello-pipeline, runID=16b95bd1-dcab-4799-9d75-5345910efc1c, task="say-hello", component="comp-say-hello", dagExecutionID=14, componentSpec) failed: failure while getting executionCache: failed to list tasks: rpc error: code = Unimplemented desc = unknown method ListTasksV1 for service api.TaskService
time="2024-02-10T01:08:50.613Z" level=info msg="sub-process exited" argo=true error="<nil>"
```

**Comment by thesuperzapper** [comment]
@pbasov first, I want to clarify that `v2.0.0-alpha7` is not actually able to run Kubeflow Pipelines `v2` pipelines, it's only able to run `v1` and `v2-compatible` pipelines. The version numbers are ridiculously confusing, I know.

Second, deployKF actually already has a way to override the `kfp-launcher` image (for `v2-compatible` pipelines, not `v2`) using the [`kubeflow_tools.pipelines.kfpV2.launcherImage`](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/default_values.yaml#L1808-L1812) value, which configures [this Kyverno ClusterPolicy](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/templates/manifests/kubeflow-tools/pipelines/resources/patch-v2-workflow-pods-clusterpolicy.yaml) to mutate the Pods at runtime.

**Comment by pbasov** [comment]
> I want to clarify that v2.0.0-alpha7 is not actually able to run Kubeflow Pipelines v2 pipelines, it's only able to run v1 and v2-compatible pipelines. The version numbers are ridiculously confusing, I know.

I find the whole kf dsl system ridicilously confusing, tbh. Feels like it's supposed to make ML engineer's life easier, but it's exact opposite.

> [kubeflow_tools.pipelines.kfpV2.launcherImage](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/default_values.yaml#L1808-L1812) value, which configures [this Kyverno ClusterPolicy](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/templates/manifests/kubeflow-tools/pipelines/resources/patch-v2-workflow-pods-clusterpolicy.yaml) to mutate the Pods at runtime

This is really cool, gotta RTFM, consider this matter closed, then.

**Comment by sebracs** [comment]
> Second, deployKF actually already has a way to override the `kfp-launcher` image (for `v2-compatible` pipelines, not `v2`) using the [`kubeflow_tools.pipelines.kfpV2.launcherImage`](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/default_values.yaml#L1808-L1812) value, which configures [this Kyverno ClusterPolicy](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/templates/manifests/kubeflow-tools/pipelines/resources/patch-v2-workflow-pods-clusterpolicy.yaml) to mutate the Pods at runtime.

Does this mean we can run a Kubeflow Pipeline v2 (newer than `2.0.0-alpha.7` from 1 year ago)?
What does "for `v2-compatible` pipelines, not `v2`" mean?

**Comment by thesuperzapper** [comment]
> > Second, deployKF actually already has a way to override the `kfp-launcher` image (for `v2-compatible` pipelines, not `v2`) using the [`kubeflow_tools.pipelines.kfpV2.launcherImage`](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/default_values.yaml#L1808-L1812) value, which configures [this Kyverno ClusterPolicy](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/templates/manifests/kubeflow-tools/pipelines/resources/patch-v2-workflow-pods-clusterpolicy.yaml) to mutate the Pods at runtime.
> 
> Does this mean we can run a Kubeflow Pipeline v2 (newer than `2.0.0-alpha.7` from 1 year ago)? What does "for `v2-compatible` pipelines, not `v2`" mean?

@sebracs it's a bit confusing, Kubeflow Pipelines version `2.0.0-alpha.7` included a mode called `v2-compatible` which was like a "beta test" for the full `v2`. That is to say, you can't use `v2` right now with deployKF `v0.1`, you must use `pip install kfp==1.8.22` (which supports both `v1` and `v2-compatible`, but NOT `v2` pipelines).

When deployKF `v0.2` is released, it will include Kubeflow Pipelines `v2` (which may or may not fully support `v1` pipelines, so users may want to stay on deployKF `v0.1` until they are ready to upgrade).
