### ISSUE TITLE
Allow for adding additional hosts to istio ingress gateway

### ISSUE THREAD

**Issue by aaronwjha** [deployKF/deployKF#111]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This request is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### Motivation

We would like to expose additional services in our kf cluster through the Istio ingress gateway. The ability to add hostnames to the gateway created by deployKF would be very helpful.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@aaronwjha Can you clarify if you just mean exposing them (in a network sense) on the same gateway, or if you want to put them behind deployKF's authentication?

If it's the former, then you can already do this by simply creating the required `Gateway` and `VirtualService` objects which select the `deploykf-gateway` Pods in the `deploykf-istio-gateway ` Namespace. (NOTE: the default labels for the Pod are defined by [`deploykf_core.deploykf_istio_gateway.gateway.selectorLabels`](https://github.com/deployKF/deployKF/blob/v0.1.4/generator/default_values.yaml#L762-L764))

However, similar to what is described for users who [bring their own gateway](https://www.deploykf.org/guides/dependencies/istio/#use-an-existing-gateway-deployment), if you have `deploykf_core.deploykf_istio_gateway.gateway.tls.matchSNI` set to `false` (which is required when you terminate TLS in our outer proxy, like AWS ALB), your custom `Gateway` resource will need to define HTTP/HTTPS ports that are NOT the same as deployKF's [`deploykf_core.deploykf_istio_gateway.gateway.ports`](https://github.com/deployKF/deployKF/blob/v0.1.4/generator/default_values.yaml#L715-L724).

Then, in your Kubernetes Ingress (or whatever you are using), you will need to use hostname routing to route to the correct backend port depending on the request's domain.

---

Also, if you want to then put a link to your custom stuff in the deployKF sidebar, see the [Customize the Dashboard](https://www.deploykf.org/guides/platform/deploykf-dashboard/) guide.

**Comment by aaronwjha** [comment]
Thanks for the help here. I was able to get my service exposed by adding a GW and VS. And you has already documented this very well. Sorry for the interruption.
