### ISSUE TITLE
sync_argocd_apps.sh has an unbound variable: _out_of_sync_apps

### ISSUE THREAD

**Issue by quloos** [deployKF/deployKF#125]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.4

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Description

when variable _out_of_sync_apps is an empty array, it always comes with an error: 

![image](https://github.com/deployKF/deployKF/assets/123724726/2a8deecf-7c63-4157-a9cb-155e90be7a47)

I found a [post](https://www.reddit.com/r/bashonubuntuonwindows/comments/7sbjce/why_are_empty_arrays_treated_as_unset_in_wsl_bash/) from reddit that might cause the error.

**Comment by thesuperzapper** [comment]
@quloos can you confirm how you're running this? I I assume you're running on WSL? 

Also, can you try the newest version of the sync script to confirm it still happens (get the latest version from the `main` branch).

**Comment by quloos** [comment]
> @quloos can you confirm how you're running this? I I assume you're running on WSL?
> 
> Also, can you try the newest version of the sync script to confirm it still happens (get the latest version from the `main` branch).

I am running on CentOS7.

And the newest version of sync script won't help.

![image](https://github.com/deployKF/deployKF/assets/123724726/b1b785e1-dc83-4d4d-9b50-5092d6d6ab10)

At the first time I run the sync script, there's no error, because for every `sync_wave`, variable `_out_of_sync_apps` is not empty. When I try to resync, the argocd app `deploykf-app-of-apps` has a Synced status, variable `_out_of_sync_apps` is an empty array, bash script fails.

**Comment by quloos** [comment]
See [this](https://stackoverflow.com/questions/48394251/why-are-empty-arrays-treated-as-unset-in-bash)

Upgrade bash should fix this.

**Comment by thesuperzapper** [comment]
@quloos I must have mistakenly put the minimum version of bash as 4.2 when it actually should be 4.4. 

Would this be a problem for you? Is it possible to update the version of bash on your server?

**Comment by quloos** [comment]
all good, thx

**Comment by thesuperzapper** [comment]
@quloos thanks for the report, I have updated the minimum `bash` version check to 4.4+ in https://github.com/deployKF/deployKF/pull/126
