### ISSUE TITLE
Kyverno admission hooks failed while following quick start guide.

### ISSUE THREAD

**Issue by haiminh2001** [deployKF/deployKF#183]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

 v1.26.6+k3s1 

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", Go
Version:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6+k3s1", GitCommit:"3b1919b0d55811707bd1168f0abf11cccc656c26", GitTreeState:"clean", BuildDate:"2023-06-26T17:51:14Z
", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Description

I am following the quick start guide with the Manifests Repo Mode. I installed the default kyverno version (helm chart version 3.0.1 and kyverno version 1.10.0). I have changed nothing in comparison with the quick start guide, but I encountered multiple kyverno admission webhooks failed with different policies, detailed logs are attached below. I reckon that adding permissions to the kyverno role/cluster role should fix my issues but since I am following the guides and I do not have many experiences with kyverno, I do no want to do so. 
By the way, the installation procedure before the kyverno issues was easy and simple :)) I think deployKF really make the cumbersome kubeflow easier to install. Although I am new to deployKF and deployKF is also a young project itself, I think I would use it to integrate Kubeflow for my company. I would really appreciate any support from you guys.

### Relevant Logs

```shell
# deploykf-mysql--restart-on-secret-updates
Sync operation to c26f3c011ba4429045df6ecaf26f34f7988d9217 failed: one or more objects failed to apply, reason: error when replacing "/dev/shm/130393359": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].generate.clone..: failed to get the Group Version Resource for kind Secret,error when replacing "/dev/shm/1998112630": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].generate.clone..: failed to get the Group Version Resource for kind Secret 

# deploykf-auth--clone-minio-openid-secret
error when replacing "/dev/shm/1998112630": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].generate.clone..: failed to get the Group Version Resource for kind Secret

# deploykf-auth--clone-argo-server-openid-secret

error when replacing "/dev/shm/130393359": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].generate.clone..: failed to get the Group Version Resource for kind Secret



# deploykf-minio--restart-on-secret-updates

admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].mutate.targets.: auth check fails, require additional privileges, update the ClusterRole 'kyverno:background-controller:additional':failed to get the Group Version Resource for kind Deployment; failed to get the Group Version Resource for kind Deployment
```

**Comment by cameronraysmith** [comment]
I also started receiving something that looks like https://github.com/kyverno/kyverno/issues/6287 in a cluster that's been operating for over a year.

**Comment by haiminh2001** [comment]
Upgrading kyverno's helm chart version from 3.0.1 (default) to 3.0.9 fixed my issue.

**Comment by thesuperzapper** [comment]
@haiminh2001 be very careful about updating Kyverno, because I can confirm that all versions of Kyverno other than 1.10.0 will not work properly (secret will not be cloned, and automatic restarts will not happen when secrets are updated).

We are also talking about Kyverno in https://github.com/deployKF/deployKF/issues/180#issuecomment-2235258937.

My plan is to remove the dependency on Kyverno for cloning secrets, which should allow us to update to the latest version, because most of its problems are related to its `generate` type rules.

**Comment by haiminh2001** [comment]
@thesuperzapper thank you for your reminder, I hope that changing only minor version should not cause any issue. From my experiences, kyverno and cert-manager integration is complicated when there is a pre-installed version in the cluster. They should be removed or expose some config to work with the pre-installed dependencies.

**Comment by thesuperzapper** [comment]
@haiminh2001 it actually does matter, you must use Kyverno 1.10.0 with deployKF 0.1.5.

Please see the [dependency version matrix](https://www.deploykf.org/releases/version-matrix/#kyverno) for more information about why every other version does not work.

**Comment by haiminh2001** [comment]
@thesuperzapper yes I closed this Issue too soon. I rollbacked Kyverno to 1.10.0, the original issue came back. I found this log in the kyverno's admission controller pod:
```
webhooks/policy/validate "msg"="policy validation errors" "error"="path: spec.rules[0].generate.clone..: failed to get the Group Version Resource for kind Secret" "gvk"={"group":"kyverno.io","version":"v1","kind":"ClusterPolicy"} "gvr"={"group":"kyverno.io","version":"v1","resource":"clusterpolicies"} "name"="clone-profile-bucket-secret-d81b8cd1-team-1-prod" "namespace"="" "operation"="UPDATE" "uid"="3720e3c8-dc2c-4be3-84b5-9f77cc8a6254" "user"={"username":"system:serviceaccount:argo-cd:argocd-application-controller","uid":"6262ad31-dada-4a7c-9740-df93f1c558df","groups":["system:serviceaccounts","system:serviceaccounts:argo-cd","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["argo-cd-argocd-application-controller-0"],"authentication.kubernetes.io/pod-uid":["68c7c668-3a26-47e2-a7c3-92db784b2ec6"]}}
```

**Comment by tommynguyen-vungle** [comment]
> Upgrading kyverno's helm chart version from 3.0.1 (default) to 3.0.9 fixed my issue.

This fixed the issue for me, altho I have to manually edit in the argoCD UI. Thanks @haiminh2001

**Comment by haiminh2001** [comment]
> > Upgrading kyverno's helm chart version from 3.0.1 (default) to 3.0.9 fixed my issue.
> 
> This fixed the issue for me, altho I have to manually edit in the argoCD UI. Thanks @haiminh2001

Be careful, as @thesuperzapper said that you must use Kyverno 1.10.0 with deployKF 0.1.5. I ended up using that version now. The issue still exists but I can simply downscale kyverno's controllers to zero to bypass. This walk-around is ok to me since it is only needed the first time I deploy.
