### ISSUE TITLE
Kubeflow Pipeline is stuck in error stage 

### ISSUE THREAD

**Issue by xwt-ml** [deployKF/deployKF#186]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
1.30
```

### Description

After successfully triggering a simple kubeflow pipline with kfp v1 with the following example code https://github.com/kubeflow/examples/blob/master/pipelines/simple-notebook-pipeline/Simple%20Notebook%20Pipeline.ipynb. 

I can see from the logs of the pod that the pipeline job is completed. But I keep getting the following error which also prevents the pipeline goes further to next steps.

`This step is in Error state with this message: Error (exit code 1): pods "calculation-pipeline-xxxx-xxxx" is forbidden: User "system:serviceaccount:<user-namespace>:default-editor" cannot patch resource "pods" in API group "" in the namespace "<user-namespace>"`

It seems that the service account `default-editor` in the user-namespace requires some special permission, but I did not find it in the installation instructions.

### Relevant Logs

```shell
time="2024-07-24T14:12:39.382Z" level=info msg="capturing logs" argo=true
0.0 + 7.0 = 7.0
time="2024-07-24T14:12:40.386Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2024-07-24T14:12:40.386Z" level=info msg="/tmp/outputs/Output/data -> /var/run/argo/outputs/parameters//tmp/outputs/Output/data" argo=true
time="2024-07-24T14:12:40.386Z" level=info msg="/tmp/outputs/Output/data -> /var/run/argo/outputs/artifacts/tmp/outputs/Output/data.tgz" argo=true
time="2024-07-24T14:12:40.386Z" level=info msg="Taring /tmp/outputs/Output/data"
```

**Comment by xwt-ml** [comment]
After some digging, I found out that the error is caused by a missing Role with patch right and a missing RoleBinding in the user namespace. I have created them manually and the pipeline run works successfully. I wonder why the required Role and RoleBinding were not installed automatically in the profile namespace when it is standard needed for the pipeline run? @thesuperzapper

**Comment by cmarquezrusso** [comment]
Hi @xwt-ml 
I am dealing with the same issue in both k8s 1.29 and k8s 1.30
On my case, the  `default-editor` service account doesn't exist and the deploykf sync script fails while syncing  `kf-tools--pipelines`
Questions:
- Is this a fresh installation of deploykf 0.1.5? or an upgrade from a previous version?
- Have you got KFP enabled? If yes, did this fail during the sync of `kf-tools--pipelines`?

**Comment by xwt-ml** [comment]
> Hi @xwt-ml I am dealing with the same issue in both k8s 1.29 and k8s 1.30 On my case, the `default-editor` service account doesn't exist and the deploykf sync script fails while syncing `kf-tools--pipelines` Questions:
> 
> * Is this a fresh installation of deploykf 0.1.5? or an upgrade from a previous version?
> * Have you got KFP enabled? If yes, did this fail during the sync of `kf-tools--pipelines`?

I created the service account `default-editor` myself before synchronisation. 
I have upgraded my platform from 0.1.4 to 0.1.5.
I have enabled kubeflow pipeline, the sync failed at the beginning once because of the PodDefault configuration but have gone through later after I deactivate the PodDefault and reactive it again.

**Comment by thesuperzapper** [comment]
@xwt-ml @cmarquezrusso I think there are two different issues being discussed here:

## Problem 1:

For some reason thee `default-editor` ServiceAccount does not have the correct permission. 

Can you do the following.

- The `profile-controller` (in the `dkf-core--deploykf-dashboard` app) is responsible for creating the `default-editor` ServiceAccounts. Please check if the profile controller Pods are happy, and share any error logs.

- If you manually created the `default-editor` ServiceAccount or RoleBinding, you might need to delete them and let the profile-controller recreate them. Remember that you need to use the [profile-generator values](https://www.deploykf.org/guides/platform/deploykf-profiles/#profile-definitions) to create Profiles, otherwise deploKF will not be aware of them.

## Problem 2: 

If the `kubeflow_tools.pipelines.profileResourceGeneration.kfpApiTokenPodDefault` is true on the first install, the `kf-tools--pipelines` Application will fail to sync the first time.

This is because the PodDefault CRD may not be applied yet depending on the random order in which apps are synced.

Fixing this is straightforward, and will be in the next version of deployKF. We can simply add a new sync wave for `kf-tools--poddefaults-webhook` which always syncs before `kf-tools--pipelines`, I have raised a PR to do this:

- https://github.com/deployKF/deployKF/pull/189

In the meantime, just run the sync script again if it fails on first sync.

**Comment by cmarquezrusso** [comment]
# Problem 1
`profile-controller`'s pods are happy. I couldn't see the Service Account as a resource under ArgoCD or in the logs.

Logs:
```
I0730 21:40:27.163830       1 request.go:601] Waited for 1.038214043s due to client-side throttling, not priority and fairness, request: GET:https://172.16.0.1:443/apis/wgpolicyk8s.io/v1alpha2?timeout=32s
1.722375627271154e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.7223756272713933e+09	INFO	setup	starting manager
1.7223756272717695e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.7223756272717986e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:9876"}
1.722375627271889e+09	INFO	Starting EventSource	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "source": "kind source: *v1.Profile"}
1.7223756272719018e+09	INFO	Starting EventSource	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "source": "kind source: *v1.Namespace"}
1.7223756272719061e+09	INFO	Starting EventSource	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "source": "kind source: *v1beta1.AuthorizationPolicy"}
1.7223756272719092e+09	INFO	Starting EventSource	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "source": "kind source: *v1.ServiceAccount"}
1.722375627271912e+09	INFO	Starting EventSource	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "source": "kind source: *v1.RoleBinding"}
1.7223756272719169e+09	INFO	Starting EventSource	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "source": "channel source: 0xc00043ea00"}
1.722375627271927e+09	INFO	Starting Controller	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile"}
1.7223756273730109e+09	INFO	Starting workers	{"controller": "profile", "controllerGroup": "kubeflow.org", "controllerKind": "Profile", "worker count": 1}
1.7223756273733323e+09	INFO	controllers.Profile	Start to Reconcile.	{"profile": "/xxx", "namespace": "", "name": "xxx"}
1.7223756273733847e+09	INFO	controllers.Profile	List of labels to be added to namespace	{"profile": "/xxx", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.7223756273734267e+09	INFO	controllers.Profile	namespace already exist, but not owned by profile creator admin@example.com	{"profile": "/xxx"}
[...]
```
I am currently testing a downgrade to deploykf 0.1.4 to see if this fixes the issues, but I got error with other components like:
- Minio
```
 Error: Drive /minio-data, path (.minio.sys/pool.bin) returned an error (decodeXLHeaders: Unknown xl header version 2) (*fmt.wrapError)
```
- MySQL 
```
│ 2024-07-30T23:12:49.991804Z 1 [ERROR] [MY-013171] [InnoDB] Cannot boot server version 80033 on data directory built by version 80037. Downgrade is not supported
```

I've deleted these components in order to get a fresh install. I will continue testing with KFP enabled and let you know if the issue persists.

<img width="906" alt="image" src="https://github.com/user-attachments/assets/0628c9a6-33e3-4720-ba5d-d1a4d08fcbc5">

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/5a1ac7cd-7e03-44d2-9054-518719ce0d83">

**Comment by cmarquezrusso** [comment]
`DeployKF 0.1.4` didnt fix the issue as the service account is still missing. I couldnt find useful information in the logs. 
I tried also by removing the `dkf-core--deploykf-dashboard` app and reinstalling it, but still facing the same issue.
Is there a way to force the creation of it?
Next try is to uninstall `deploykf` and try again (starting with `deploykf 0.1.4` and upgrading to `0.1.5`)

**Comment by cmarquezrusso** [comment]
I managed to get the `service-account` created by deleting my namespace, which was created after cluster creation and before `deploykf` was installed. This was done in order to add existing PVCs for EFS.

As soon as I restarted the `profile-controller` pod, I got this:

```
[...]
1.7223910234990516e+09	INFO	controllers.Profile	Start to Reconcile.	{"profile": "/user1", "namespace": "", "name": "user1"}
1.7223910234990807e+09	INFO	controllers.Profile	List of labels to be added to namespace	{"profile": "/user1", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.722391023499117e+09	INFO	controllers.Profile	namespace already exist, but not owned by profile creator admin@example.com	{"profile": "/user1"}
1.7223910235070343e+09	INFO	controllers.Profile	Start to Reconcile.	{"profile": "/user2", "namespace": "", "name": "user2"}
1.7223910235070488e+09	INFO	controllers.Profile	List of labels to be added to namespace	{"profile": "/user2", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.722391023507066e+09	INFO	controllers.Profile	Creating Namespace: cristian	{"profile": "/user2"}
1.7223910235252697e+09	INFO	controllers.Profile	Created Namespace: cristian	{"profile": "/user2", "status": "Active"}
1.722391023525387e+09	INFO	controllers.Profile	Creating Istio AuthorizationPolicy	{"profile": "user2", "namespace": "user2", "name": "ns-owner-access-istio"}
1.7223910235551002e+09	INFO	controllers.Profile	Creating ServiceAccount	{"profile": "user2", "namespace": "user2", "name": "default-editor"}
1.7223910235639603e+09	INFO	controllers.Profile	Creating RoleBinding	{"profile": "user2", "namespace": "user2", "name": "default-editor"}
1.7223910235718145e+09	INFO	controllers.Profile	Creating ServiceAccount	{"profile": "user2", "namespace": "user2", "name": "default-viewer"}
1.722391023578254e+09	INFO	controllers.Profile	Creating RoleBinding	{"profile": "user2", "namespace": "user2", "name": "default-viewer"}
1.7223910235868342e+09	INFO	controllers.Profile	Creating RoleBinding	{"profile": "user2", "namespace": "user2", "name": "namespaceAdmin"}
1.7223910236972265e+09	INFO	controllers.Profile	No update on resource quota	{"profile": "/user2", "spec": "&ResourceQuotaSpec{Hard:ResourceList{},Scopes:[],ScopeSelector:nil,}"}
1.7223910237159514e+09	INFO	KubeAPIWarningLogger	metadata.finalizers: "profile-finalizer": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
[...]
```

On my previous installation (when everything was working) I created the namespaces and PVCs after installing `deploykf`

**Comment by xwt-ml** [comment]
> @xwt-ml @cmarquezrusso I think there are two different issues being discussed here:
> 
> ## Problem 1:
> For some reason thee `default-editor` ServiceAccount does not have the correct permission.
> 
> Can you do the following.
> 
> * The `profile-controller` (in the `dkf-core--deploykf-dashboard` app) is responsible for creating the `default-editor` ServiceAccounts. Please check if the profile controller Pods are happy, and share any error logs.
> * If you manually created the `default-editor` ServiceAccount or RoleBinding, you might need to delete them and let the profile-controller recreate them. Remember that you need to use the [profile-generator values](https://www.deploykf.org/guides/platform/deploykf-profiles/#profile-definitions) to create Profiles, otherwise deploKF will not be aware of them.
> 
> ## Problem 2:
> If the `kubeflow_tools.pipelines.profileResourceGeneration.kfpApiTokenPodDefault` is true on the first install, the `kf-tools--pipelines` Application will fail to sync the first time.
> 
> This is because the PodDefault CRD may not be applied yet depending on the random order in which apps are synced.
> 
> Fixing this is straightforward, and will be in the next version of deployKF. We can simply add a new sync wave for `kf-tools--poddefaults-webhook` which always syncs before `kf-tools--pipelines`, I have raised a PR to do this:
> 
> * [fix: race condition between PodDefaults and KFP sync #189](https://github.com/deployKF/deployKF/pull/189)
> 
> In the meantime, just run the sync script again if it fails on first sync.

Hi @thesuperzapper , to problem 1: I have checked the status of profile controller Pods, it is healthy and there is no error logs. As you suggested, I deleted the service account `default-editor`, the Role and the RoleBinding that I created manually. And I made sure that the profile namespace is defined in the profile-generator values in the value YAML file. After syncing the apps again, no service accounts, Roles or RoleBindings are recreated, even though the sync was completed successfully.

**Comment by cmarquezrusso** [comment]
@xwt-ml `profile-controller` doesn't show errors in the logs (at least for myself)
Can u check that the namespace has the right labels and ownership permissions? Do you have this in the logs? `namespace already exist, but not owned by profile creator `

**Comment by xwt-ml** [comment]
@cmarquezrusso , thanks for the hint. The namespace was indeed not owned by the profile creator. By adding the annotation and resync the apps, the service account and rolebinding were created successfully. But this also erase all notebooks created in the namespace before. 
Additionally @thesuperzapper, I would like to mention that the installation instruction on the Deploykf page is unclear to me whether I need to create the service account myself or just the IAM role with the required policy. The AWS reference link you pointed to is actually a guide to create the service account oneself.

**Comment by thesuperzapper** [comment]
> @cmarquezrusso , thanks for the hint. The namespace was indeed not owned by the profile creator. By adding the annotation and resync the apps, the service account and rolebinding were created successfully. But this also erase all notebooks created in the namespace before. Additionally @thesuperzapper, I would like to mention that the installation instruction on the Deploykf page is unclear to me whether I need to create the service account myself or just the IAM role with the required policy. The AWS reference link you pointed to is actually a guide to create the service account oneself.

@xwt-ml can you clarify where in the docs we say to manually create `default-editor`?

Or at least where it's confusing, so we can fix it?

**Comment by xwt-ml** [comment]
> > @cmarquezrusso , thanks for the hint. The namespace was indeed not owned by the profile creator. By adding the annotation and resync the apps, the service account and rolebinding were created successfully. But this also erase all notebooks created in the namespace before. Additionally @thesuperzapper, I would like to mention that the installation instruction on the Deploykf page is unclear to me whether I need to create the service account myself or just the IAM role with the required policy. The AWS reference link you pointed to is actually a guide to create the service account oneself.
> 
> @xwt-ml can you clarify where in the docs we say to manually create `default-editor`?
> 
> Or at least where it's confusing, so we can fix it?

The command marked in red rectangle will create the namespace and the service account automatically. I thought I should apply the same command also for the profiles. It would be helpful to mention when only IAM role with trust identity is required and when a service account should be created by the users.
<img width="818" alt="Bildschirmfoto 2024-08-05 um 17 25 05" src="https://github.com/user-attachments/assets/2b7b1aea-66f5-41e1-af17-d8c07b6be0cc">
