### ISSUE TITLE
Cannot get MLMD objects from Metadata store.

### ISSUE THREAD

**Issue by xwt-ml** [deployKF/deployKF#187]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
1.29
```

### Description

A simple "hello world" example cannot be started successfully in the kubeflow pipeline with kfp v2.
The following error message keeps showing
`Cannot get MLMD objects from Metadata store.`
This issue is related to https://github.com/kubeflow/pipelines/issues/8733 and https://github.com/kubeflow/pipelines/issues/8733.

**Comment by haiminh2001** [comment]
Hi @xwt-ml, have you found any solution ? I saw on the kubeflow github that it should be fixed with kubeflow 1.9.0, but deployKF seem to not be able to upgrade kubeflow version.

**Comment by xwt-ml** [comment]
I downgraded the kfp to use 1.8.22. Have not found a solution to work with kfp 2.0.

**Comment by thesuperzapper** [comment]
@xwt-ml @haiminh2001 can you please try restarting the `Deployment/metadata-envoy-deployment` in the kubeflow namespace?

I see from others that there is some kind of race condition on that pod which causes this error.

Run the following command to do the restart:

```bash
kubectl rollout restart deployment/metadata-envoy-deployment --namespace kubeflow
```

**Comment by thesuperzapper** [comment]
Assuming that restarting that Pod fixes it, I have made a PR to add a livenessProbe which will do it automatically:

- https://github.com/deployKF/deployKF/pull/191

**Comment by haiminh2001** [comment]
> @xwt-ml @haiminh2001 can you please try restarting the `Deployment/metadata-envoy-deployment` in the kubeflow namespace?
> 
> I see from others that there is some kind of race condition on that pod which causes this error.
> 
> Run the following command to do the restart:
> 
> ```shell
> kubectl rollout restart deployment/metadata-envoy-deployment --namespace kubeflow
> ```

I also saw that issue yesterday from charmed kubeflow, I did restart the deployment and now it worked. But I am not 100% sure that restarting did the trick because I was applying other changes too. But adding probes can only benefit so I think you should definitely add the probes.

**Comment by xwt-ml** [comment]
@thesuperzapper , I restarted the `metadata-envoy-deployment` and run a simple "hello world" example with kfp 2.0 in a new profile namespace. I do not get the error message "cannot get MLMD objects from Metadata store" anymore. But the simple "hello world" run is stuck in error state without any error message shown in the logs. 
<img width="1412" alt="Bildschirmfoto 2024-08-05 um 18 10 38" src="https://github.com/user-attachments/assets/02bcd672-017d-4d07-8cbe-0e5feee446ac">
The pod is in "complete" status and here is the pod logs:
```
time="2024-08-05T16:04:28.388Z" level=info msg="capturing logs" argo=true
I0805 16:04:28.440439      17 main.go:108] input ComponentSpec:{
  "dag": {
    "tasks": {
      "hello-world": {
        "cachingOptions": {
          "enableCache": true
        },
        "componentRef": {
          "name": "comp-hello-world"
        },
        "inputs": {
          "parameters": {
            "text": {
              "componentInputParameter": "text"
            }
          }
        },
        "taskInfo": {
          "name": "hello-world"
        }
      }
    }
  },
  "inputDefinitions": {
    "parameters": {
      "text": {
        "defaultValue": "hi there",
        "isOptional": true,
        "parameterType": "STRING"
      }
    }
  }
}
I0805 16:04:28.441261      17 main.go:121] input ContainerSpec:{}
I0805 16:04:28.441329      17 main.go:128] input RuntimeConfig:{
  "parameterValues": {
    "text": "hi there"
  }
}
I0805 16:04:28.441402      17 main.go:136] input kubernetesConfig:{}
I0805 16:04:28.441935      17 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow.svc.cluster.local:8887
I0805 16:04:28.456787      17 driver.go:149] PipelineRoot="s3://deploykf-artifacts-bucket/v2/artifacts/pdf-full?region=eu-west-1&endpoint=s3.amazonaws.com&disableSSL=false&s3ForcePathStyle=true" from default config
I0805 16:04:28.574363      17 client.go:290] Pipeline Context: id:12 name:"hello-world" type_id:17 type:"system.Pipeline" create_time_since_epoch:1722873868535 last_update_time_since_epoch:1722873868535
I0805 16:04:28.692664      17 client.go:298] Pipeline Run Context: id:13 name:"040431e4-a6fb-406d-b1fd-12cc2a780ac3" type_id:18 type:"system.PipelineRun" custom_properties:{key:"namespace" value:{string_value:"pdf-full"}} custom_properties:{key:"pipeline_root" value:{string_value:"s3://deploykf-artifacts-bucket/v2/artifacts/pdf-full/hello-world/040431e4-a6fb-406d-b1fd-12cc2a780ac3?region=eu-west-1&endpoint=s3.amazonaws.com&disableSSL=false&s3ForcePathStyle=true"}} custom_properties:{key:"resource_name" value:{string_value:"run-resource"}} create_time_since_epoch:1722873868651 last_update_time_since_epoch:1722873868651
I0805 16:04:28.851189      17 driver.go:172] Created execution: id:18 name:"run/040431e4-a6fb-406d-b1fd-12cc2a780ac3" type_id:19 type:"system.DAGExecution" last_known_state:RUNNING custom_properties:{key:"display_name" value:{string_value:""}} custom_properties:{key:"inputs" value:{struct_value:{fields:{key:"text" value:{string_value:"hi there"}}}}} custom_properties:{key:"task_name" value:{string_value:""}} create_time_since_epoch:1722873868805 last_update_time_since_epoch:1722873868805
I0805 16:04:28.851296      17 main.go:202] output execution.ID=18
time="2024-08-05T16:04:29.391Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2024-08-05T16:04:29.391Z" level=info msg="/tmp/outputs/execution-id -> /var/run/argo/outputs/parameters//tmp/outputs/execution-id" argo=true
time="2024-08-05T16:04:29.391Z" level=info msg="/tmp/outputs/iteration-count -> /var/run/argo/outputs/parameters//tmp/outputs/iteration-count" argo=true
time="2024-08-05T16:04:29.391Z" level=info msg="/tmp/outputs/condition -> /var/run/argo/outputs/parameters//tmp/outputs/condition" argo=true
```
Any idea what the problem is? The kfp1.0 pipeline still works without problem.

**Comment by xwt-ml** [comment]
I restarted `deployment/metadata-envoy-deployment` and run a kfp2.0 pipeline in a new profile namespace. It works fine without the error.
