### ISSUE TITLE
Is there support for AWS Fargate?

### ISSUE THREAD

**Issue by clay-risser** [deployKF/deployKF#21]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This request is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### Motivation

Support fargate

### Implementation

Is there support for farget?

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [ ] I can help test the feature!

**Comment by thesuperzapper** [comment]
@clay-risser thanks for raising this, I am interested to know what is not working on Fargate with version 0.1.1, so we can resolve it.

Are you able to test on Fargate for us?

**Comment by clay-risser** [comment]
It seems fargate is too limited to run most of kubeflow.

The best alternative is karpenter.

https://karpenter.sh
